### ISSUE TITLE
FB.ui and getLoginStatus

### ISSUE THREAD

**Issue by Abhinav-Duggal** [Thuzi/facebook-winjs-sdk#3]
Hey, just curious, will it support the FB.ui and getLoginStatus functions?

**Comment by prabirshrestha** [comment]
not currently as we leave the devs to store the access token.

You can see the sample at https://github.com/Thuzi/facebook-winjs-sdk-sample

**Comment by Abhinav-Duggal** [comment]
So if I want to say post on user's friend's wall then since facebook eliminated post queries using feed using the graph api...the only thing I could have done is to create a feed dialog, but since there's no FB.ui function , so there's no support for that...is there an alternative way using this sdk then? (becoz the sample doesn't show it)
