### ISSUE TITLE
issue with FB.ui not being there

### ISSUE THREAD

**Issue by Abhinav-Duggal** [Thuzi/facebook-winjs-sdk#4]
So if I want to say post on user's friend's wall from my winJS app then since facebook eliminated post queries using feed using the graph api...the only thing I could have done is to create a feed dialog, but since there's no FB.ui function , so there's no support for that...is there an alternative way using this sdk then? (becoz the sample doesn't show it)

this is the error using FB.api call to post on the user's friend's wall
  "error": 
{
    "message": 
"(#200) Feed story publishing to other users is disabled for this application", 
    "type": 
"OAuthException", 
    "code": 
200
  }
}

**Comment by prabirshrestha** [comment]
create custom ui and use graph api.

please post these type of questions in stackoverflow.

**Comment by Abhinav-Duggal** [comment]
Can you please elaborate on how one would go about making a custom ui function for winjs..I am trying to develop an app using your SDK which is the only SDK for WinJS and i want facebook integration with the above mentioned functionality... Any help will be greatly appreciated
